import FooterLinks from "@/components/footer/FooterLinks";
import SimpleHeader from "@/components/header/SimpleHeader";
import SearchProvider from "@/components/search/SearchProvider";
import { ColorScheme, ColorSchemeProvider, Container, MantineProvider } from "@mantine/core";
import { useLocalStorage } from "@mantine/hooks";
import { SessionProvider } from "next-auth/react";
import { AppProps } from "next/app";
import Head from "next/head";

const MyApp = ({ Component, pageProps: props }: AppProps) => {
	const { session, ...pageProps } = props;
	const [colorScheme, setColorScheme] = useLocalStorage<ColorScheme>({
		key: "color-scheme",
		defaultValue: "light",
		getInitialValueInEffect: true,
	});

	const toggleColorScheme = (value?: ColorScheme) => setColorScheme(value || (colorScheme === "dark" ? "light" : "dark"));

	return (
		<>
			<Head>
				<title>Page title</title>
				<meta name='viewport' content='minimum-scale=1, initial-scale=1, width=device-width' />
				<meta name='viewport' content='width=device-width, initial-scale=1, maximum-scale=1' />
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<ColorSchemeProvider colorScheme={colorScheme} toggleColorScheme={toggleColorScheme}>
				<MantineProvider withGlobalStyles withNormalizeCSS theme={{ colorScheme }}>
					<SessionProvider session={session}>
						<SearchProvider>
							<div
								style={{
									minHeight: "100vh",
									display: "grid",
									gridTemplateRows: "auto 1fr auto",
								}}>
								<SimpleHeader />
								<Container
									size='sm'
									mb='xl'
									style={{ overflowX: "hidden", paddingBottom: "10px", width: "100%" }}>
									<Component {...pageProps} />
								</Container>
								<FooterLinks />
							</div>
						</SearchProvider>
					</SessionProvider>
				</MantineProvider>
			</ColorSchemeProvider>
		</>
	);
};

export default MyApp;
