import SimpleHeader from "@/components/header/SimpleHeader";
import SearchProvider from "@/components/search/SearchProvider";
import { Container, MantineProvider } from "@mantine/core";
import { AppProps } from "next/app";
import Head from "next/head";

const MyApp = (props: AppProps) => {
	const { Component, pageProps } = props;

	return (
		<>
			<Head>
				<title>Page title</title>
				<meta name='viewport' content='minimum-scale=1, initial-scale=1, width=device-width' />
				<meta name='viewport' content='width=device-width, initial-scale=1, maximum-scale=1' />
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<MantineProvider
				withGlobalStyles
				withNormalizeCSS
				theme={{
					/** Put your mantine theme override here */
					colorScheme: "light",
				}}>
				<SearchProvider>
					<SimpleHeader />
					<Container size='sm' mb='xl' style={{ overflowX: "hidden" }}>
						<Component {...pageProps} />
					</Container>
				</SearchProvider>
			</MantineProvider>
		</>
	);
};

export default MyApp;
